name: server
description: The Dart Frog server for Votasq
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  dart_frog: ^1.1.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  shared: any # Automatically resolved via workspace

dev_dependencies:
  dart_frog_lint: ^0.1.0
  test: ^1.25.5
