name: client
description: The Flutter client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

resolution: workspace

dependencies:
  bloc: ^9.2.0
  cloud_firestore: ^5.0.0 # Official FlutterFire
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.20.2
  shared: any # Use the same shared logic as the server

dev_dependencies:
  bloc_lint: ^0.3.7
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.22
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
