// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnm4GFvZv0sAIHgAErcPT_k6f87J7VR9s',
    appId: '1:269624680910:android:fb1c08a507f982d1124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYSIsIXqC4u0MyaVd07wTG-nvAIdnl7Hs',
    appId: '1:269624680910:web:33a9d10d05a7a28f124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    authDomain: 'votasq-190fd.firebaseapp.com',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeuKG7R64HBXkVqVyZv-i4L6aR2r_G_oE',
    appId: '1:269624680910:ios:3b37d6293e192f2b124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
    iosBundleId: 'net.quikchange.votasq',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeuKG7R64HBXkVqVyZv-i4L6aR2r_G_oE',
    appId: '1:269624680910:ios:facee32ee03ee929124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
    iosBundleId: 'net.quikchange.votasq.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYSIsIXqC4u0MyaVd07wTG-nvAIdnl7Hs',
    appId: '1:269624680910:web:88c33e44cf910895124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    authDomain: 'votasq-190fd.firebaseapp.com',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCYSIsIXqC4u0MyaVd07wTG-nvAIdnl7Hs',
    appId: '1:269624680910:web:33a9d10d05a7a28f124b9f',
    messagingSenderId: '269624680910',
    projectId: 'votasq',
    authDomain: 'votasq-190fd.firebaseapp.com',
    databaseURL: 'https://votasq-190fd.firebaseio.com',
    storageBucket: 'votasq.firebasestorage.app',
  );
}
